"""add_keywords_to_title_metadata

Revision ID: 1db8fa14de36
Revises: dea0cacdf16b
Create Date: 2026-01-16 09:48:24.536185

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1db8fa14de36"
down_revision: str | Sequence[str] | None = "dea0cacdf16b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("title_metadata", sa.Column("keywords", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("title_metadata", "keywords")
    # ### end Alembic commands ###
