"""Initial schema

Revision ID: dea0cacdf16b
Revises:
Create Date: 2026-01-15 15:35:17.549331

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dea0cacdf16b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("agencies_parent_id_fkey"), "agencies", type_="foreignkey")
    op.create_foreign_key(None, "agencies", "agencies", ["parent_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "agencies", type_="foreignkey")
    op.create_foreign_key(
        op.f("agencies_parent_id_fkey"), "agencies", "agencies", ["parent_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###
